# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "HifDocument",
]

@typing.final
class HifDocument:
    @staticmethod
    def from_json(raw: builtins.str) -> HifDocument:
        r"""
        Parse and validate HIF without requiring viewer compatibility.
        """
    @staticmethod
    def load(path: builtins.str) -> HifDocument:
        r"""
        Load HIF offline from a UTF-8 JSON file.
        """
    @staticmethod
    def from_hypergraph_json(raw: builtins.str) -> HifDocument:
        r"""
        Export native hypergraph.v1 JSON to a new HIF document.
        """
    def to_json(self) -> builtins.str:
        r"""
        Serialize all HIF properties, including unsupported viewer semantics.
        """
    def save(self, path: builtins.str) -> None:
        r"""
        Save all HIF properties as UTF-8 JSON.
        """
    def to_hypergraph_json(self) -> builtins.str:
        r"""
        Convert to viewer JSON, rejecting unsupported semantics and weight overflow.
        """
